# Generated by Django 6.0.5 on 2026-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='retry_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
