# Generated by Django 6.0.5 on 2026-05-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_grace_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='item_rec_date_next',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='item_rec_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
