# Generated by Django 6.0.5 on 2026-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenttransaction_rec_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='', max_length=20),
        ),
    ]
